package cloudflare

import (
	"fmt"
	"net"
	"sort"
	"strconv"
	"strings"

	"github.com/zoefix/openfrp/internal/config"
)

type Rule struct {
	Hostname string
	Service  string
}

func RulesFor(tunnels []config.Tunnel) (rules []Rule, skipped []string) {
	for _, tunnel := range tunnels {
		if !tunnel.Enabled {
			continue
		}

		if tunnel.Type != config.TunnelHTTP && tunnel.Type != config.TunnelHTTPS {
			skipped = append(skipped, fmt.Sprintf("%s (%s)", tunnel.Name, tunnel.Type))
			continue
		}
		if len(tunnel.Domains) == 0 {
			skipped = append(skipped, fmt.Sprintf("%s (no domain)", tunnel.Name))
			continue
		}

		service := serviceURL(tunnel)
		for _, domain := range tunnel.Domains {
			rules = append(rules, Rule{Hostname: domain, Service: service})
		}
	}

	sort.SliceStable(rules, func(i, j int) bool {
		return specificity(rules[i].Hostname) > specificity(rules[j].Hostname)
	})

	return rules, skipped
}

func specificity(hostname string) int {
	labels := strings.Count(hostname, ".") + 1
	if strings.HasPrefix(hostname, "*.") {
		return labels
	}
	return labels + 1000
}

func serviceURL(tunnel config.Tunnel) string {
	host := tunnel.LocalIP
	if host == "" {
		host = "127.0.0.1"
	}
	return "http://" + net.JoinHostPort(host, strconv.Itoa(tunnel.LocalPort))
}

func RenderConfig(tunnelID, credentialsPath string, rules []Rule) string {
	var out strings.Builder

	out.WriteString("# Generated by openfrp. Edits are overwritten.\n")
	fmt.Fprintf(&out, "tunnel: %s\n", quote(tunnelID))
	fmt.Fprintf(&out, "credentials-file: %s\n", quote(credentialsPath))

	out.WriteString("loglevel: info\n")
	out.WriteString("no-autoupdate: true\n")
	out.WriteString("ingress:\n")

	for _, rule := range rules {
		fmt.Fprintf(&out, "  - hostname: %s\n", quote(rule.Hostname))
		fmt.Fprintf(&out, "    service: %s\n", quote(rule.Service))
	}

	out.WriteString("  - service: http_status:404\n")

	return out.String()
}

func quote(value string) string {
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range value {
		switch r {
		case '"':
			out.WriteString(`\"`)
		case '\\':
			out.WriteString(`\\`)
		case '\n':
			out.WriteString(`\n`)
		default:
			out.WriteRune(r)
		}
	}
	out.WriteByte('"')
	return out.String()
}
