package server

import (
	"fmt"
	"net"
	"strings"
	"sync"
	"time"
)

// challengePrefix is the path an ACME HTTP-01 validation is fetched from.
const challengePrefix = "/.well-known/acme-challenge/"

// challengeTTL bounds how long an unanswered challenge is remembered.
//
// This is the only backstop. A challenge is published from a connection that
// hangs up immediately afterwards, so a disconnect cannot mean "forget this" —
// which leaves an issuance that dies before withdrawing its own challenge with
// nothing but time to clean up after it. The authority validates within
// seconds of being asked, so an hour is generous by orders of magnitude and
// still finite.
const challengeTTL = time.Hour

// ChallengeStore holds the ACME HTTP-01 challenges clients have published.
//
// The server answers these itself on the shared HTTP port rather than
// forwarding them down a tunnel. That is what makes HTTP validation usable
// here: the router has no public address, the name already points at this
// server, and the LAN service — which may not exist yet, and would need
// configuring if it did — is never involved.
type ChallengeStore struct {
	mu     sync.RWMutex
	tokens map[string]challenge
}

type challenge struct {
	keyAuth  string
	domain   string
	runID    string
	deadline time.Time
}

// NewChallengeStore returns an empty store.
func NewChallengeStore() *ChallengeStore {
	return &ChallengeStore{tokens: map[string]challenge{}}
}

// Publish records one challenge on behalf of a client.
func (s *ChallengeStore) Publish(runID, domain, token, keyAuth string) error {
	if token == "" || keyAuth == "" {
		return fmt.Errorf("server: an HTTP challenge needs a token and a key authorisation")
	}
	// The token becomes a URL path element. Anything that could escape it is
	// refused rather than sanitised, because a token is generated by the
	// authority and never contains such a character legitimately.
	if strings.ContainsAny(token, "/?#\\ ") {
		return fmt.Errorf("server: %q is not a usable challenge token", token)
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	s.expireLocked()
	s.tokens[token] = challenge{
		keyAuth:  keyAuth,
		domain:   domain,
		runID:    runID,
		deadline: time.Now().Add(challengeTTL),
	}
	return nil
}

// Withdraw removes a challenge. Only the client that published it may.
func (s *ChallengeStore) Withdraw(runID, token string) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if existing, ok := s.tokens[token]; ok && existing.runID == runID {
		delete(s.tokens, token)
	}
}

// Answer returns the key authorisation for a request path, if one is published.
func (s *ChallengeStore) Answer(path string) (string, bool) {
	if !strings.HasPrefix(path, challengePrefix) {
		return "", false
	}

	token := strings.TrimPrefix(path, challengePrefix)
	if token == "" || strings.Contains(token, "/") {
		return "", false
	}

	s.mu.RLock()
	defer s.mu.RUnlock()

	found, ok := s.tokens[token]
	if !ok || time.Now().After(found.deadline) {
		return "", false
	}
	return found.keyAuth, true
}

// Len reports how many challenges are outstanding.
func (s *ChallengeStore) Len() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.tokens)
}

// expireLocked drops challenges nobody withdrew. Called on publish rather than
// from a timer: challenges arrive rarely, so there is no reason to keep a
// goroutine awake for them.
func (s *ChallengeStore) expireLocked() {
	now := time.Now()
	for token, existing := range s.tokens {
		if now.After(existing.deadline) {
			delete(s.tokens, token)
		}
	}
}

// answerChallenge writes the validation response.
//
// Deliberately a complete, minimal HTTP/1.1 response with Connection: close.
// The authority makes one request and reads one response; keeping the
// connection alive would only leave a socket for it to time out.
func answerChallenge(conn net.Conn, keyAuth string) {
	fmt.Fprintf(conn,
		"HTTP/1.1 200 OK\r\n"+
			"Content-Type: text/plain\r\n"+
			"Content-Length: %d\r\n"+
			"Connection: close\r\n\r\n%s",
		len(keyAuth), keyAuth)
}
